### ISSUE TITLE
Suggestion: auto-reset server idle time

### ISSUE THREAD

**Issue by Haarolean** [TF2Stadium/QA#25]
As far as I know, Arie, owner of serveme.tf, allowed tf2center to use sv_tag "tf2center" to keep reservation opened while server is used in lobby and with it you don't need to reset the idle timer.
Also I know he cooperates with TF2Pickup, so, probably, you can try to ask him about same tag, for example :)

**Comment by gpittarelli** [comment]
Would you look at that, serveme already supports a `TF2Stadium` tag!

https://github.com/Arie/serveme/blob/f7ae6ecd72f917daed4cbb08c295194f246982ba/app/models/reservation.rb#L204

I'll add this to Pauling (the TF2 server manager service) now, so that we're actually setting that tag for serveme to check.

**Comment by Haarolean** [comment]
Would be nice. I made this suggestion just because I remember the note somewhere on site like 'don't forget about your reservation' :)

**Comment by gpittarelli** [comment]
Solved by:
https://github.com/TF2Stadium/TF2RconWrapper/pull/9
https://github.com/TF2Stadium/Pauling/pull/11
